# TODO: add monorepo features
# TODO: move repeated code into some alias

version: 2
jobs:
  build_serverless:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/project/serverless

    steps:
      - checkout:
          path: ~/project

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo yarn global add serverless
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Deploy application
          command: sls deploy

  build-graphql:
    docker:
      - image: circleci/node:11.11

    working_directory: ~/project/graphql

    steps:
      - checkout:
          path: ~/project

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - deploy:
          command: |
            yarn now --token $ZEIT_TOKEN

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn now --token $ZEIT_TOKEN alias
            fi
workflows:
  version: 2
  build:
    jobs:
      - build_serverless
      - build-graphql
