version: 2
jobs:
  build_serverless:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/project/serverless

    steps:
      - checkout:
          path: ~/project

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo yarn global add serverless
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Deploy application
          command: sls deploy

workflows:
  version: 2
  build:
    jobs:
      - build_serverless
