version: 2
jobs:
  build_serverless:
    docker:
      - image: circleci/node:8.10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "serverless/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo yarn global add serverless
            cd serverless && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "serverless/package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: cd serverless && yarn test

      - run:
          name: Deploy application
          command: cd serverless && sls deploy

workflows:
  version: 2
  build:
    jobs:
      - build_serverless
